export default appConstants = {
    ENGLISH: 'English',
    THAI: 'Thai',
    MYANMAR: 'Myanmar',
    CAMBODIA: 'Cambodia',
    LAOS: 'Laos',
    PLEASE_INSERT_YOUR_PHONE_NUMBER: 'Please enter your phone number',
    PLEASE_INSERT_YOUR_FRIEND_PHONE_NUMBER: "Please enter your friend's phone number",
    DOESENT_HAVE_PHONE_NUMBER: "Don't have phone number ?",
    WELCOME_TO_SWM: 'Welcome to SWM',
    CREATE_ACCOUNT: 'CREATE ACCOUNT',
    LOGIN_AS_COMPANY: 'LOGIN AS A COMPANY',
    LOGIN_AS_LABOR: 'LOGIN AS A LABOR',
    SIGNUP_AS_COMPANY: 'SIGNUP AS A COMPANY',
    SIGNUP_AS_LABOR: 'SIGNUP AS A LABOR',
    EMAIL_OR_PHONE_NUMBER: 'Email or phone number',
    PHONE_NUMBER: 'Phone number',
    PASSWORD: 'Password',
    LOGIN: 'LOGIN',
    SUMBIT: 'SUMBIT',
    CLOSE: 'CLOSE',
    FORGOT_PASSWORD: 'FORGOT PASSWORD',
    NEW_PASSWORD: 'Add New Password',

    DONT_HAVE_AN_ACCOUNT: "Don't have an account?",
    PHONE: 'Phone',
    NEXT: 'NEXT',
    CANCEL: 'Cancel',
    OK: 'Ok',
    VERIFICATION_CODE: 'Verification Code',
    VERIFICATION_MESSAGE1: 'Please enter the 4 digit code that you just',
    VERIFICATION_MESSAGE2: 'received in your phone ',
    ENTER_OTP_CODE: 'Enter OTP Code',
    NAME: 'Name',
    FRIEND_NAME: "Your friend's name",

    EMAIL: 'Email',
    COMPANY_NAME: 'Company Name',
    POSITION: 'Position',
    TYPE_OF_COMPANY: 'Type of Company',
    SIZE_OF_COMPANY: 'Size of Company',
    ALERADY_HAVE_AN_ACCOUNT: 'Already have an account?',
    SIGN_IN: 'Sign in',
    TYPE_OF_COMPANY: 'Type of Company',
    COMPANY_ADDRESS: 'Company Address',
    NUMBER_OF_LABORS: 'Number of Labors',
    SELECT_LABORS_NATIONALITY: 'Select Labors Nationality',
    PASSWORD: 'Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    SIGN_UP: 'SIGN UP',
    CONFIRM: 'Confirm',
    NO_THIS_INFORMATION_IS_WRONG: 'No, this information is wrong',
    FORGOT_MESSAGE1: 'Enter your email address associated with your',
    FORGOT_MESSAGE2: 'account we will send you a link to reset your',
    FORGOT_MESSAGE3: 'password',
    MY_ACCOUNT: 'My Account',
    ABOUT_US: 'About Us',
    CONTACT_US: 'Contact Us',
    CHANGE_LANGUAGE: 'Change Language',
    FAQ: 'FAQ',
    LOGOUT: 'Logout',
    NATIONALITY: 'Nationality',
    EDIT: 'Edit',
    SELECT_NATIONALITY: 'Select nationality',
    SELECT_FRIEND_NATIONALITY: "Select your friend's nationality",

    EMLOPYER: 'Employer',
    NETWORK_ERROR: 'Sorry, something went wrong, please try again in sometime.',
    ADD_DOCUMENT: 'Add Document',
    UPLOAD: 'UPLOAD',
    NO_THANKS_I_WILL_SCAN_LATER: 'No thanks - I will scan later',
    MY_DOCUMENTS: 'My Documents',
    FRIENDS: 'Friends',
    DELETE: 'Delete',
    ISSUES: 'Issues',
    PASSPORT: 'Passport',
    NEEDS_REVIEW: 'Needs Review',
    VISA: 'Visa',
    WORK_PERMIT: 'Work Permit',
    NINETY_DAYS: '90 Days',
    REPORT_OR_STAY: 'Report or Stay',
    ID_CARD: 'Id Card',
    SEARCH: 'Search',
    ADD_FRIEND: 'Add Friend',
    ADD_PICTURE: 'Add Picture',
    ADD: 'Add',
    FRIEND_DETAIL: 'FRIEND DETAIL',
    CHAT: 'CHAT',
    PROCESSING: 'Processing',
    CLOSE_TO_EXPIRE: 'Close to Expire',
    EXPIRED: 'Expired',
    OK: 'Ok',
    TYPE_A_MESSAGE: 'Type a message',
    VIEW: 'View',
    LABORS: 'Labors',
    INSIGHTS: 'Insights',
    REPORTS: 'Reports',
    ADD_LABOR: 'Add Labor',
    EDIT_LABOR: 'Edit Labor',
    DOCUMENTS: 'Documents',
    EMPLOYEE: 'Employee',
    LOADING: 'Loading...',
    STATUS: 'Status',
    DOWNLOAD_ALL: 'Download All',
    OUR_SERVICES: 'Our Services',
    COMPANY: 'Company',
    LABOR_NATIONALITY: 'Labor nationality',
    SAVE: 'SAVE',
    SENDING_OTP: 'Sending OTP to entered phone number....',
    EMAIL_REQUIRED: 'Please enter email or phone number.',
    PASSWORD_REQUIRED: 'Please enter password.',
    PASSWORD_STRONG_ERROR: 'Password contain 6 characters with atleast 1 lowercase, 1 uppercase, 1 numeric, 1 special character.',
    EMPTY_PHONE_FIELD_MESSAGE: 'Please enter phone number.',
    VALID_PHONE_MESSAGE: 'Please enter valid phone number.',
    PLEASE_TRY_AGAIN: 'Please try again.',
    PLEASE_ENTER_OTP: 'Please enter OTP.',
    PLEASE_ENTER_EMAIL: 'Please enter an email.',
    PLEASE_ENTER_VALID_EMAIL: 'Please enter valid email.',
    PLEASE_ENTER_OLD_PASSWORD: 'Please enter old password.',
    PLEASE_ENTER_NEW_PASSWORD: 'Please enter new password.',
    PLEASE_ENTER_VALID_OLD_PASSWORD: 'Please enter valid old password.',
    PLEASE_ENTER_NAME: 'Please enter name.',
    PLEASE_ENTER_VALID_NAME: 'Please enter a valid name.',
    NAME_MUST_CONTAIN_ATLEAST_TWO_CHARACTER: 'Name must contain atleast two character.',
    PLEASE_ENTER_COMPANY_NAME: 'Please enter company name.',
    PLEASE_ENTER_VALID_COMPANY_NAME: 'Please enter a valid company name.',
    COMPANY_NAME_MUST_CONTAIN_ATLEAST_TWO_CHARACTER: 'Company name must contain atleast two character',
    PLEASE_SELECT_COMPANY_TYPE: 'Please select compant type.',
    PLEASE_SELECT_COMPANY_SIZE: 'Please select companysize.',
    PLEASE_ENTER_NUMBER_OF_LABOR: 'Please enter number of labors.',
    PASSWORD_VALIDATE: 'Your password must be at least 8 characters long, contain at least one number and have a mixture of uppercase and lowercase letters.',
    MATCH_PASSWORD: 'Password and confirm password not matched.',
    PLEASE_ENTER_ADDRESS: 'Please enter address.',
    PLEASE_ENTER_CONFIRM_PASSWORD: 'Please enter confirm password.',
    PLEASE_ENTER_NATIONALITY: 'Please enter nationality.',
    PLEASE_ENTER_POSITION: 'Please enter position.',
    PLEASE_ENTER_VALID_POSITION_NAME: 'Please enter valid position name',
    POSITION_NAME_MUST_CONTAIN_ATLEAST_TWO_CHARACTER: 'Position name must contain atleast 2 character.',
    PLEASE_ENTER_EMPLOYER_NAME: 'Please enter employer name.',
    PLEASE_ENTER_VALID_EMPLOYER_NAME: 'Please enter valid employer name.',
    EMPLOYER_NAME_MUST_CONTAIN_ATLEAST_TWO_CHARACTER: 'Employer name must contain atleast 2 character.',
    UNAUTHORISED_USER_ACCESS: 'Unauthorised user access.',
    ADDRESS_MUST_CONTAIN_ATLEAST_THREE_CHARACTER: 'Address must contain atleast three character.',
    SORRY_YOU_DO_NOT_HAVE_ANY_LABORS: 'Sorry, you do not have any labors.',
    PLEASE_WAIT: 'Please wait ....',
    NO_RESULT_FOUND: 'Sorry, no result found.',
    UPDATE: 'Update',
    EDIT_PROFILE: 'EDIT PROFILE',
    NO_ISSUES_FOUND: 'No issues found.',
    SORRY_YOU_DO_NOT_HAVE_ANY_FRIRNDS: 'Sorry you do not have any friends.',
    EDIT_FRIEND: 'Edit Friend',
    TAKE_PHOTO: 'Take Photo...',
    CHOOSE_FROM_LIBRARY: 'Choose from Library...',
    PLEASE_SELECT_YOUR_LANGUAGE: 'Please select your language',
    GIVEN_NAMES: 'Given Names',
    WHICH_TYPE_OF_JOB_YOU_DO_IN: 'Type of work/unemployed ',
    I_WILL_SEND_TO_YOU_THE_LIST_LATER: 'I will send to you the list later',
    SELECT_JOB_TYPE: 'Select job type',
    DO_YOU_HAVE_AN_EMAIL: 'Please type your email',
    WHERE_ELSE_WE_CAN_CONTACT_YOU: 'Where else we can contact you ?',
    YES: 'Yes',
    NO: 'No',
    NO_I_LOST_IT: 'No, I lost it',
    DO_YOU_KNOW_THE_NAME_OF_THE_PLACE_WHERE_YOU_WORK_AT: 'Do you know the name of the place where you work at?',
    OR: 'Or',
    DO_YOU_KNOW_THE_NAME_OF_YOUR_EMPLOYER: 'Do you know the name of your employer?',
    I_DONT_KNOW: "I don't know",
    PLACE: 'Place',
    EMPLOYER_NAME: 'Employer name',
    MOU: 'MOU',
    ADD_DETAILS: 'Add Details',
    DONE: 'DONE',
    REQUEST_NEW_DOCUMENT: 'Request New Document',
    ADD_NEW: 'Add New',
    DO_YOU_HAVE_YOUR_PASSPORT_WITH_YOU: 'Do you have your passport with you ? ',
    PLEASE_SCAN_YOUR_PASSPORT_TO_CREATE_YOUR_ACCOUCT: 'Please scan your passport to create your account',
    PLEASE_CONFIRM_IF_THE_INFORMATION_BELOW_IS_CORRECT: 'Please confirm if the information below is correct',
    WHICH_DOCUMENT_DO_YOU_NEED: 'Which document do you need?',
    PLEASE_SCAN_YOUR_PASSPORT: 'Please scan your passport',
    ARE_YOU_SURE: 'Are you sure?',
    IF_YOU_DECIDE_NOT_TO_SCAN_YOU_WILL_NEED_TO_TYPE_YOUR_PASSPORT_INFORMATION_MANUALLY: '(If you decide not to scan, you will need to type your passport information manually)',
    I_DONT_HAVE_A_JOB: "I DON'T HAVE A JOB",
    DONT_HAVE_A_JOB :'Don’t Have a job',
    MESSENGER_FACEBOOK: 'Messenger (Facebook)',
    LINE: 'Line',
    SKIP: 'Skip',
    WHICH_CITY_ARE_YOU_IN: 'Which city are you in?',
    WHICH_CITY_ARE_YOUR_FRIEND_IN: 'Which city is your friend in?',

    WHERE_DO_YOU_WORK_IN_THAILAND: 'Where do you work in Thailand?',
    WHERE_DO_YOU_LIVE_IN_THAILAND: 'Where do you live in Thailand?',

    WHICH_TYPE_OF_JOB_FRIEND_WORK_IN_THAILAND: 'Which type of job does your friend do in',
    CITY: 'City',
    DO_YOU_KNOW_THE_PHONE_NUMBER_OF_YOUR_EMPLOYER_MANAGER: 'Please type the phone number that you used to register your account',
    WHERE_YOUR_FRIEND_WORK_THILAND: 'Where does your friend work in Thailand?',
    WHERE_YOUR_FRIEND_LIVE_THILAND: 'Where does your friend live in Thailand?',

    SCAN_YOUR_FRIENDS_PASSPORT: "Please scan your friend's passport",
    FRIEND_NATIONALITY:"Please select your friend's nationality",
    CHANGED_PHONE_NUMBER: 'Changed Phone Number?',
    SECURITY_QUESTION: 'Security Question',
    OLD_PHONE_NUMBER: 'Old phone number',
    PASSPORT_NUMBER: 'Passport Number',
    BIRTHDATE_SHOWN_IN_PASSPORT: 'Please type your birthdate as in your passport',
    "DD/MM/YYYY": "DD/MM/YYYY",
    "PLACE_OF_BIRTH_SHOWN_IN_PASSPORT": "Please type your birthplace as in your passport",
    "BIRTH_PLACE": "Birth place",
    "NEW_PHONE_NUMBER": "New phone number",
    "REMIND_PASSPORT_SCAN": "Looks like you forgot to scan your passport!!! Please upload your passport.",

    PLEASE_SELECT_ANY_OPTION: 'Please select any one option',

    QUESTION: 'Question',
    CURRENT_RANK: 'Current Rank',
    CURRENT_SCORE: 'CURRENT SCORE',
    SCORE:'Score',
    TOP_RANKS: 'Top Ranks',
    PLEASE_ENTER_EMAIL: 'Please enter email',
    PLEASE_ENTER_VALID_EMAIL: 'Please enter valid email',
    SET_PASSWORD_DESCRIPTION: 'Password needs to be set for a private contest. Keeping it blank will make your contest Public to all.',
    CHANGE_PASSWORD_DESC: 'Please enter your registered mail and we will send OTP for same.',
    CHANGE_PASSWORD_BUTTON: 'Change',
    CONTESTANTS: 'Contestants',
    SAVE_TO_NOT_FOUND: 'You do not have any groups created yet for you profile',

    WORDS_TEXT: 'Words',

    WALK_SCREEN_TITLE_1: 'How to play on Murabbo?',
    WALK_SCREEN_TITLE_2: 'How to play on Murabbo?',
    WALK_SCREEN_TITLE_3: 'How to play on Murabbo?',

    WALK_SCREEN_SUB_TITLE_1: 'Create',
    WALK_SCREEN_SUB_TITLE_2: 'Share & Host',
    WALK_SCREEN_SUB_TITLE_3: 'Play',

    WALK_SCREEN_DESC_1: 'Few minutes to create your Contest for learning or entertainment.',
    WALK_SCREEN_DESC_2: 'Host a live Contest with rounds and questions in an in-person mode or share and play it interactively over a video call with remote players.',
    WALK_SCREEN_DESC_3: 'Select Precreated Challanges or Join a Contest with a PIN provided by a Moderator and start playing over a video call.',


    SUBSCRIPTION_MESSAGE: 'You need to purchase subscription.',
}