export default actionType = {
    LOADER: 'LOADER',
    PULL_REFRESH: 'PULL_REFRESH',
    PHONE: 'PHONE',
    ALERT: 'ALERT',
    LOGIN_DETAILS: 'LOGIN_DETAILS',
    ERROR_MESSAGE: 'ERROR_MESSAGE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    USER_DETAILS: 'USER_DETAILS',
    USER_TOKEN: 'USER_TOKEN',
    LOGIN_ROLE: 'LOGIN_ROLE',
    LOGOUT: 'LOGOUT',
    PROFILE: 'PROFILE',
    COUNTRY_CODE: 'COUNTRY_CODE',

    //Contest ActionType
    BRAND_SELCTED_LIST: 'BRAND_SELCTED_LIST',
    CATEGORY_SELCTED_LIST: 'CATEGORY_SELCTED_LIST',
    BRAND_LIST: 'BRAND_LIST',
    CATEGORY_LIST: 'CATEGORY_LIST',
    GAMES_LIST: 'GAMES_LIST',
    GAME_LIST: 'GAME_LIST',
    GROUP_LIST: 'GROUP_LIST',
    NOTIFICATIONS: 'NOTIFICATIONS',

    // Playing round states
    SET_PLAYABLE_ROUNDS: 'SET_PLAYABLE_ROUNDS',
    SET_CURRENT_ROUND: 'SET_CURRENT_ROUND',


    // video calling
    JOIN_CHAT: "JOIN_CHAT",
    ADD_STREAM: "ADD_STREAM",
    MY_STREAM: "MY_STREAM",
    ADD_REMOTE_STREAM: "ADD_REMOTE_STREAM",
    REMOVE_REMOTE_STREAM: "REMOVE_REMOTE_STREAM",
    UPDATE_REMOTE_STREAM: "UPDATE_REMOTE_STREAM",
    ADD_VIDEO_USERID: "ADD_VIDEO_USERID",
    REMOVE_VIDEO_USERID: "REMOVE_VIDEO_USERID",
    TOGGLE_MUTE_USER: "TOGGLE_MUTE_USER",
    ADD_USERS_LIST: "ADD_USERS_LIST",
    FLUSH_USERS_LIST: "FLUSH_USERS_LIST",
    FLUSH_DATA: "FLUSH_DATA",

    // new video requested user
    VIDEO_CLIENT_USERS_REQUEST_ADD: "VIDEO_CLIENT_USERS_REQUEST_ADD",
    VIDEO_CLIENT_REQ_DONE: "VIDEO_CLIENT_REQ_DONE",
    VIDEO_MODERATOR_LEAVE_ROOM: "VIDEO_MODERATOR_LEAVE_ROOM",
    CHANGE_QUALIFY_STATUS: "CHANGE_QUALIFY_STATUS",
    LOADER_FOR_REQUEST_MODERATOR: "LOADER_FOR_REQUEST_MODER",


    // subscription store
    GET_SUBSCRIBE_DATA: "GET_SUBSCRIBE_DATA",

    // notification store
    NOTIFICATION_TEXT: "NOTIFICATION_TEXT",


    // game store
    GAME_START_STATUS: "GAME_START_STATUS",
    GAME_CLIENT_USERS: "GAME_CLIENT_USERS",
    GAME_FLUSH_DATA: "GAME_FLUSH_DATA",
    GAME_MODERATOR_STATUS: "GAME_MODERATOR_STATUS",
    GAME_LAST_ANS_RESULT: "GAME_LAST_ANS_RESULT",
    GAME_LAST_SERVER_RESULT: "GAME_LAST_SERVER_RESULT",
    GAME_ASSIGNED_USER: "GAME_ASSIGNED_USER",
    GAME_CLIENT_USERS_REQUEST_ADD: "GAME_CLIENT_USERS_REQUEST_ADD",
    GAME_CLIENT_USERS_REQUEST_REMOVE: "GAME_CLIENT_USERS_REQUEST_REMOVE",
    GAME_CLIENT_USERS_REQUEST_ACCEPT_STATUS: "GAME_CLIENT_USERS_REQUEST_ACCEPT_STATUS",
    GAME_MODERATOR_LEAVE_ROOM: "GAME_MODERATOR_LEAVE_ROOM",
    GAME_MODERATOR_NEXT_ROOM_COMP: "GAME_MODERATOR_NEXT_ROOM_COMP",
    DEEP_LINK_STATUS: "DEEP_LINK_STATUS",

    // questions store
    CONTEST_MAX_QUESTION_GET: "CONTEST_MAX_QUESTION_GET"
}