export default {
    bgSplash: require('../assets/images/bgSplash.png'),
    lock: require('../assets/images/lock.png'),
    message: require('../assets/images/message.png'),
    user: require('../assets/images/user.png'),
    logoSplash: require('../assets/images/logoSplash.png'),
    loginLogo: require('../assets/images/loginLogo.png'),
    backLogo: require('../assets/images/backLogo.png'),
    facebook: require('../assets/images/facebook.png'),
    gmail: require('../assets/images/gmail.png'),

    checkmark: require('../assets/images/checkmark.png'),
    dashboard: require('../assets/images/dashboard.png'),
    search: require('../assets/images/search.png'),
    create: require('../assets/images/create.png'),
    menu: require('../assets/images/menu.png'),
    logoText: require('../assets/images/logoText.png'),
    people: require('../assets/images/people.png'),
    imgbackground: require('../assets/images/imgbackground.png'),
    imgBackgounddYello: require('../assets/images/imgBackgounddYello.png'),
    imgBackgoundGreen: require('../assets/images/imgBackgoundGreen.png'),
    imgBackgroundPink: require('../assets/images/imgBackgroundPink.png'),
    imgBackgroundRed: require('../assets/images/imgBackgroundRed.png'),
    imgBackgroundYe: require('../assets/images/imgBackgroundYe.png'),
    imgBackgroundTaboo: require('../assets/images/imgBackgroundTaboo.png'),

    yellowBg: require('../assets/images/yellowBg.png'),

    candy: require('../assets/images/candy.png'),
    pubg: require('../assets/images/pubg.png'),
    counter: require('../assets/images/counter.jpg'),
    info: require('../assets/images/info.png'),
    check: require('../assets/images/check.png'),
    apple: require('../assets/images/apple.png'),
    key: require('../assets/images/key.png'),
    keybg: require('../assets/images/keybg.png'),
    dashboar: require('../assets/images/dashboar.png'),
    creaate: require('../assets/images/creaate.png'),
    more: require('../assets/images/more.png'),
    search_selected: require('../assets/images/search_selected.png'),
    dice: require('../assets/images/dice.png'),
    background: require('../assets/images/background.png'),
    checkmark: require('../assets/images/checkmark.png'),
    games: require('../assets/images/gamind.png'),
    crossCircle: require('../assets/images/crossCircle.png'),
    crossSmall: require('../assets/images/cross_small.png'),
    upload: require('../assets/images/upload.png'),
    clock: require('../assets/images/clock.png'),
    minus: require('../assets/images/minus.png'),
    pluss: require('../assets/images/pluss.png'),
    help: require('../assets/images/help.png'),
    send: require('../assets/images/send.png'),

    console: require('../assets/images/console.png'),
    mark: require('../assets/images/mark.png'),
    backArrow: require('../assets/images/backArrow.png'),
    email: require('../assets/images/email.png'),
    crossCir: require('../assets/images/crossCir.png'),
    title: require('../assets/images/title.png'),
    paper: require('../assets/images/paper.png'),
    searchWhite: require('../assets/images/searchWhite.png'),

    hashtag: require('../assets/images/hashtag.png'),
    global: require('../assets/images/global.png'),
    plusY: require('../assets/images/plusY.png'),
    checkSolid: require('../assets/images/checkSolid.png'),
    book: require('../assets/images/book.png'),
    enable: require('../assets/images/enable.png'),
    cube: require('../assets/images/cube.png'),
    score: require('../assets/images/score.png'),
    negativeSign: require('../assets/images/negativeSign.png'),
    downArrow: require('../assets/images/downArrow.png'),
    forwordYellow: require('../assets/images/forwordYellow.png'),
    Rectangle: require('../assets/images/Rectangle.png'),
    dot: require('../assets/images/dot.png'),
    cross: require('../assets/images/cross.png'),
    crossWhite: require('../assets/images/crossWhite.png'),
    edit: require('../assets/images/edit.png'),
    infoWhite: require('../assets/images/infoWhite.png'),
    phone: require('../assets/images/phone.png'),
    keyIcon: require('../assets/images/keyIcon.png'),
    music: require('../assets/images/music.png'),
    play: require('../assets/images/play.png'),
    cameraWhite: require('../assets/images/cameraWhite.png'),
    video: require('../assets/images/video.png'),
    audio: require('../assets/images/audio.png'),
    eye: require('../assets/images/eye.png'),
    hideEye: require('../assets/images/eye-hide.png'),


    gallary: require('../assets/images/gallary.png'),
    gear: require('../assets/images/gear.png'),
    brand1: require('../assets/images/brand1.png'),
    warning: require('../assets/images/warning.png'),
    info2: require('../assets/images/info2.png'),
    hintWhiteIcon: require('../assets/images/hintWhiteIcon.png'),
    bell: require('../assets/images/bell.png'),



    close_pink: require('../assets/images/close_pink.png'),
    filter: require('../assets/images/filter.png'),

    checkMarkSelected: require('../assets/images/check_mark_sel.png'),
    checkMarkUnSelected: require('../assets/images/check_mark_unsel.png'),

    leaderboard: require('../assets/images/leaderboard.png'),
    invitation: require('../assets/images/invitation.png'),
    calender: require('../assets/images/calendar.png'),
    logout: require('../assets/images/exit.png'),
    mygames: require('../assets/images/mygames.png'),


    dot_horizontal : require('../assets/images/dot_horizontal.png'),
    imgBackgroundMore: require('../assets/images/imgBackgroundMore.png'),
    imgBg_gibberish: require('../assets/images/imgBg_gibberish.png'),
    imgBg_quiz: require('../assets/images/imgBg_quiz.png'),
    imgbackgroundHangman: require('../assets/images/imgBg_hangman.png'),
    radio_btn_sel : require('../assets/images/round_select.png'),
    radio_btn_unselect: require('../assets/images/round_unselect.png'),

    saveTo: require('../assets/images/saveTo.png'),
    smallPlaceholder: require('../assets/images/smallPlaceholder.png'),
    bigPlaceHolder: require('../assets/images/bigPlaceHolder.png'),
    questionPlaceholder: require('../assets/images/questionPlaceholder.png'),
    roundPlaceHolder: require('../assets/images/roundPlaceholder.png'),
    addressbook: require('../assets/images/addressbook.png'),
    fbIconShare: require('../assets/images/fbIconShare.png'),
    megnifire: require('../assets/images/megnifire.png'),
    microphone: require('../assets/images/microphone.png'),
    videoCamera: require('../assets/images/video-camera.png'),
    leaderboardBG: require('../assets/images/leaderboardBG.png'),
    crownBG: require('../assets/images/crownBG.png'),
    upperArrow: require('../assets/images/upperArrow.png'),
    rightIcon: require('../assets/images/rightIcon.png'),
    diamond: require('../assets/images/diamond.png'),
    cup : require('../assets/images/cup.png'),
    instagram : require('../assets/images/instagram.png'),
    callCam: require('../assets/images/callCam.png'),
    callCamMute: require('../assets/images/callCamMute.png'),
    flipCam: require('../assets/images/Flip-Camera.png'),
    callMic : require('../assets/images/callMic.png'),
    callMicMute : require('../assets/images/callMicMute.png'),
    callRight : require('../assets/images/callRight.png'),
    callFalse : require('../assets/images/callFalse.png'),
    coin: require('../assets/images/coin.png'),
    end : require('../assets/images/end.png'),
    invitePerson : require('../assets/images/invitePerson.png'),
    speaker : require('../assets/images/speaker.png'),
    speakerMute : require('../assets/images/speakerMute.png'),
    upWhiteArrow : require('../assets/images/upWhiteArrow.png'),
    downWhiteArrow : require('../assets/images/downWhiteArrow.png'),
    facebookProfile : require('../assets/images/facebookProfile.png'),
    gplusIcon : require('../assets/images/gplusIcon.png'),
    editStatusDown : require('../assets/images/editStatusDown.png'),
    editStatusUp : require('../assets/images/editStatusUp.png'),
    away : require('../assets/images/away.png'),
    donotdisturb : require('../assets/images/donot-disturb.png'),
    invisible : require('../assets/images/invisible.png'),
    online : require('../assets/images/online.png'),
    xMark : require('../assets/images/xMark.png'),
    check_true : require('../assets/images/check_true.png'),
    vCallPlaceholder : require('../assets/images/vcallPlaceholder.jpg'),
    viewVCallUsers : require('../assets/images/viewVCallUsers.png'),
    pause : require('../assets/images/pause.png'),

    walkthrow0 : require('../assets/images/walkthrow0.png'),
    walkthrow1 : require('../assets/images/walkthrough1.png'),
    walkthrow2 : require('../assets/images/walkthrough2.png'),

    hangmanMan: require('../assets/images/hangmanMan.png'),

    pro: require('../assets/images/pro.png'),
    premium: require('../assets/images/premium.png'),

    report_flag: require('../assets/images/report_flag.png'),
    
    tempProfile: require('../assets/images/user_profile.jpg'),
    tempWatermalon: require('../assets/images/tempWatermalon.png'),
    tempCat: require('../assets/images/tempCat.png'),
    tempSparrow: require('../assets/images/tempSparrow.png'),
    tempMusic: require('../assets/images/tempMusic.png'),
    tempYoutubeIcon: require('../assets/images/tempYoutubeIcon.png'),
}